services:
  postgres:
    image: postgres:15
    container_name: batch_explorer_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: batch_explorer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migration:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: batch_explorer_migration
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/batch_explorer_db
    command: ["./migration"]
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: batch_explorer_backend
    environment:
      APP_DATABASE_URL: postgres://postgres:password@postgres:5432/batch_explorer_db
      STRATA_FULLNODE: "https://fnclientbcc5fe8c4454c314eb0a00cd3882.temp6-testnet1-staging.stratabtc.org"
      APP_FETCH_INTERVAL: 5
    ports:
      - "3000:3000"
    depends_on:
      - migration
    command: ["./batch-explorer"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: batch_explorer_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:3000
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  postgres_data: