services:
  postgres:
    image: postgres:15
    container_name: checkpoint_explorer_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: checkpoint_explorer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migration:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: checkpoint_explorer_migration
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/checkpoint_explorer_db
    command: ["./migration"]
    restart: "no"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: checkpoint_explorer_backend
    environment:
      APP_DATABASE_URL: postgres://postgres:password@postgres:5432/checkpoint_explorer_db
      STRATA_FULLNODE: "https://rpc.testnet-staging.stratabtc.org/"
      APP_FETCH_INTERVAL: 5
      RUST_LOG: "info,sqlx::query=warn"
    ports:
      - "3000:3000"
    depends_on:
      - migration
    command: ["./checkpoint-explorer"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: checkpoint_explorer_frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  postgres_data: