services:
  postgres:
    image: postgres:15
    container_name: batch_explorer_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: batch_explorer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  migration:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: batch_explorer_migration
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/batch_explorer_db
    command: ["./migration"]
    restart: "no" # Exit after running migrations

  batch-explorer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: batch_explorer_app
    environment:
      APP_DATABASE_URL: postgres://postgres:password@postgres:5432/batch_explorer_db
      STRATA_FULLNODE: "https://strataseq.temp6-testnet1-staging.stratabtc.org/"
      APP_FETCH_INTERVAL : 5
    ports:
      - "3000:3000"
    depends_on:
      - migration
    command: ["./batch-explorer"]

volumes:
  postgres_data: